export const GET_COURSES_LOAD = "GET_COURSES_LOAD";
export const GET_COURSES_FAIL = "GET_COURSES_FAIL";
export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID";
export const GET_COURSES_BY_CATEGORY = "GET_COURSES_BY_CATEGORY";
